%%
%
function [] = super_mda_function_convertMetamorph2SuperMDA(path)
mydir = dir(path);
myexpression = '(?<group_label>.+(?=_s))_s(?<position>\d+)_w(?<channel_num>\d+)(?<channel_name>.+(?=_t))_t(?<timepoint>\d+)_z(?<zlevel>\d+)\.png';
database = [];
for i = 1:length(mydir)
    if mydir(i).isdir == true
        continue;
    end
    mytokens = regexp(mydir(i).name,myexpression,'names');
    if isempty(mytokens)
        continue;
    end
    my_dataset = table(...
        cellstr(mytokens.channel_name),...
        cellstr(mydir(i).name),...
        cellstr(mytokens.group_label),...
        cellstr(''),...
        cellstr(''),...
        cellstr(mytokens.channel_num),...
        cellstr(''),...
        cellstr(''),...
        cellstr(''),...
        1,...
        1,...
        cellstr(''),...
        cellstr(mytokens.position),...
        cellstr(mytokens.position),...
        cellstr(mytokens.channel_num),...
        cellstr(mytokens.channel_num),...
        cellstr(mytokens.timepoint),...
        cellstr(''),...
        cellstr(''),...
        cellstr(''),...
        cellstr(mytokens.zlevel),...
        cellstr(''),...
        'VariableNames',{'channel_name','filename','group_label','position_label','binning','channel_number','continuous_focus_offset','continuous_focus_bool','exposure','group_number','group_order','matlab_serial_date_number','position_number','position_order','settings_number','settings_order','timepoint','x','y','z','z_order','image_description'});
        database = [database;my_dataset];
end
writetable(database,fullfile(path,'..','SuperMDA_database.txt'),'Delimiter','\t');