%%
%
classdef SuperMDATravelAgent_object2 < handle
    properties
        itinerary;
        gui_main;
        mm;
        pointerGroup = 1;
        pointerPosition = 1;
        pointerSettings = 1;
        uot_conversion = 1;
    end
    %%
    %
    methods
        %% The constructor method
        % |smdai| is the itinerary that has been initalized with the
        % micromanager core handler object
        function obj = SuperMDATravelAgent_object2(smdaITF,mm)
            %%%
            % parse the input
            q = inputParser;
            addRequired(q, 'smdaITF', @(x) isa(x,'SuperMDAItineraryTimeFixed_object'));
            addRequired(q, 'mm', @(x) isa(x,'Core_MicroManagerHandle'));
            parse(q,smdaITF,mm);
            %% Initialzing the SuperMDA object
            %
            obj.itinerary = q.Results.smdaITF;
            obj.mm = q.Results.mm;
            %% Create a gui to enable pausing and stopping
            %    ___ _   _ ___    ___              _   _
            %   / __| | | |_ _|  / __|_ _ ___ __ _| |_(_)___ _ _
            %  | (_ | |_| || |  | (__| '_/ -_) _` |  _| / _ \ ' \
            %   \___|\___/|___|  \___|_| \___\__,_|\__|_\___/_||_|
            %
            % Create the figure
            %
            myunits = get(0,'units');
            set(0,'units','pixels');
            Pix_SS = get(0,'screensize');
            set(0,'units','characters');
            Char_SS = get(0,'screensize');
            ppChar = Pix_SS./Char_SS;
            set(0,'units',myunits);
            fwidth = 136.6; %683/ppChar(3);
            fheight = 70; %910/ppChar(4);
            fx = Char_SS(3) - (Char_SS(3)*.1 + fwidth);
            fy = Char_SS(4) - (Char_SS(4)*.1 + fheight);
            f = figure('Visible','off','Units','characters','MenuBar','none','Position',[fx fy fwidth fheight],...
                'CloseRequestFcn',{@fDeleteFcn},'Name','Travel Agent Main');
            
            textBackgroundColorRegion1 = [176 224 230]/255; %PowderBlue
            buttonBackgroundColorRegion1 = [135 206 235]/255; %SkyBlue
            textBackgroundColorRegion2 = [144 238 144]/255; %LightGreen
            buttonBackgroundColorRegion2 = [50 205  50]/255; %LimeGreen
            textBackgroundColorRegion3 = [255 250 205]/255; %LemonChiffon
            buttonBackgroundColorRegion3 = [255 215 0]/255; %Gold
            textBackgroundColorRegion4 = [255 192 203]/255; %Pink
            buttonBackgroundColorRegion4 = [255 160 122]/255; %Salmon
            buttonSize = [20 3.0769]; %[100/ppChar(3) 40/ppChar(4)];
            region1 = [0 56.1538]; %[0 730/ppChar(4)]; %180 pixels
            region2 = [0 42.3077]; %[0 550/ppChar(4)]; %180 pixels
            region3 = [0 13.8462]; %[0 180/ppChar(4)]; %370 pixels
            region4 = [0 0]; %180 pixels
            
            %% Assemble Region 1
            %   ___          _            _
            %  | _ \___ __ _(_)___ _ _   / |
            %  |   / -_) _` | / _ \ ' \  | |
            %  |_|_\___\__, |_\___/_||_| |_|
            %          |___/
            %%% Time Info
            %
            hpopupmenuUnitsOfTime = uicontrol('Style','popupmenu','Units','characters',...
                'FontSize',14,'FontName','Verdana',...
                'String',{'seconds','minutes','hours','days'},...
                'Position',[region1(1)+2, region1(2)+0.7692, buttonSize(1),buttonSize(2)],...
                'Callback',{@obj.popupmenuUnitsOfTime_Callback});
            
            uicontrol('Style','text','Units','characters','String','Units of Time',...
                'FontSize',10,'FontName','Verdana','BackgroundColor',textBackgroundColorRegion1,...
                'Position',[region1(1)+2, region1(2)+4.2308, buttonSize(1),1.5385]);
            
            heditFundamentalPeriod = uicontrol('Style','edit','Units','characters',...
                'FontSize',14,'FontName','Verdana',...
                'String',num2str(obj.itinerary.fundamental_period),...
                'Position',[region1(1)+2, region1(2)+6.5385, buttonSize(1),buttonSize(2)],...
                'Callback',{@editFundamentalPeriod_Callback});
            
            uicontrol('Style','text','Units','characters','String','Fundamental Period',...
                'FontSize',10,'FontName','Verdana','BackgroundColor',textBackgroundColorRegion1,...
                'Position',[region1(1)+2, region1(2)+10, buttonSize(1),2.6923]);
            
            heditDuration = uicontrol('Style','edit','Units','characters',...
                'FontSize',14,'FontName','Verdana',...
                'String',num2str(obj.itinerary.duration),...
                'Position',[region1(1)+24, region1(2)+0.7692, buttonSize(1),buttonSize(2)],...
                'Callback',{@editDuration_Callback});
            
            uicontrol('Style','text','Units','characters','String','Duration',...
                'FontSize',10,'FontName','Verdana','BackgroundColor',textBackgroundColorRegion1,...
                'Position',[region1(1)+24, region1(2)+4.2308, buttonSize(1),1.5385]);
            
            heditNumberOfTimepoints = uicontrol('Style','edit','Units','characters',...
                'FontSize',14,'FontName','Verdana',...
                'String',num2str(obj.itinerary.number_of_timepoints),...
                'Position',[region1(1)+24, region1(2)+6.5385, buttonSize(1),buttonSize(2)],...
                'Callback',{@editNumberOfTimepoints_Callback});
            
            uicontrol('Style','text','Units','characters','String','Number of Timepoints',...
                'FontSize',10,'FontName','Verdana','BackgroundColor',textBackgroundColorRegion1,...
                'Position',[region1(1)+24, region1(2)+10, buttonSize(1),2.6923]);
            %%% Output directory
            %
            heditOutputDirectory = uicontrol('Style','edit','Units','characters',...
                'FontSize',12,'FontName','Verdana','HorizontalAlignment','left',...
                'String',num2str(obj.itinerary.output_directory),...
                'Position',[region1(1)+46, region1(2)+0.7692, buttonSize(1)*3.5,buttonSize(2)],...
                'Callback',{@editOutputDirectory_Callback});
            
            uicontrol('Style','text','Units','characters','String','Output Directory',...
                'FontSize',10,'FontName','Verdana','BackgroundColor',textBackgroundColorRegion1,...
                'Position',[region1(1)+46, region1(2)+4.2308, buttonSize(1)*3.5,1.5385]);
            
            hpushbuttonOutputDirectory = uicontrol('Style','pushbutton','Units','characters',...
                'FontSize',20,'FontName','Verdana','BackgroundColor',buttonBackgroundColorRegion1,...
                'String','...',...
                'Position',[region1(1)+48+buttonSize(1)*3.5, region1(2)+0.7692, buttonSize(1)*.5,buttonSize(2)],...
                'Callback',{@pushbuttonOutputDirectory_Callback});
            %%% Save or load current SuperMDAItinerary
            %
            hpushbuttonSave = uicontrol('Style','pushbutton','Units','characters',...
                'FontSize',14,'FontName','Verdana','BackgroundColor',buttonBackgroundColorRegion1,...
                'String','Save',...
                'Position',[region1(1)+46, region1(2)+6.5385, buttonSize(1),buttonSize(2)],...
                'Callback',{@pushbuttonSave_Callback});
            
            uicontrol('Style','text','Units','characters','String','Save an Itinerary',...
                'FontSize',10,'FontName','Verdana','BackgroundColor',textBackgroundColorRegion1,...
                'Position',[region1(1)+46, region1(2)+10, buttonSize(1),2.6923]);
            
            hpushbuttonLoad = uicontrol('Style','pushbutton','Units','characters',...
                'FontSize',14,'FontName','Verdana','BackgroundColor',buttonBackgroundColorRegion1,...
                'String','Load',...
                'Position',[region1(1)+68, region1(2)+6.5385, buttonSize(1),buttonSize(2)],...
                'Callback',{@pushbuttonLoad_Callback});
            
            uicontrol('Style','text','Units','characters','String','Load an Itinerary',...
                'FontSize',10,'FontName','Verdana','BackgroundColor',textBackgroundColorRegion1,...
                'Position',[region1(1)+68, region1(2)+10, buttonSize(1),2.6923]);
            %% Assemble Region 2
            %   ___          _            ___
            %  | _ \___ __ _(_)___ _ _   |_  )
            %  |   / -_) _` | / _ \ ' \   / /
            %  |_|_\___\__, |_\___/_||_| /___|
            %          |___/
            %%% The group table
            %
            htableGroup = uitable('Units','characters',...
                'BackgroundColor',[textBackgroundColorRegion2;buttonBackgroundColorRegion2],...
                'ColumnName',{'label','group #','# of positions','function before','function after'},...
                'ColumnEditable',logical([1,0,0,0,0]),...
                'ColumnFormat',{'char','numeric','numeric','char','char'},...
                'ColumnWidth',{30*ppChar(3) 'auto' 'auto' 30*ppChar(3) 30*ppChar(3)},...
                'FontSize',8,'FontName','Verdana',...
                'CellEditCallback',@tableGroup_CellEditCallback,...
                'CellSelectionCallback',@tableGroup_CellSelectionCallback,...
                'Position',[region2(1)+2, region2(2)+0.7692, 91.6, 13.0769]);
            %%% add or drop a group
            %
            hpushbuttonGroupAdd = uicontrol('Style','pushbutton','Units','characters',...
                'FontSize',14,'FontName','Verdana','BackgroundColor',buttonBackgroundColorRegion2,...
                'String','Add',...
                'Position',[fwidth - 4 - buttonSize(1)*1.25, region2(2)+7.6923, buttonSize(1)*.75,buttonSize(2)],...
                'Callback',{@pushbuttonGroupAdd_Callback});
            
            uicontrol('Style','text','Units','characters','String','Add a group',...
                'FontSize',10,'FontName','Verdana','BackgroundColor',textBackgroundColorRegion2,...
                'Position',[fwidth - 4 - buttonSize(1)*1.25, region2(2)+11.1538, buttonSize(1)*.75,2.6923]);
            
            hpushbuttonGroupDrop = uicontrol('Style','pushbutton','Units','characters',...
                'FontSize',14,'FontName','Verdana','BackgroundColor',buttonBackgroundColorRegion2,...
                'String','Drop',...
                'Position',[fwidth - 4 - buttonSize(1)*1.25, region2(2)+0.7692, buttonSize(1)*.75,buttonSize(2)],...
                'Callback',{@pushbuttonGroupDrop_Callback});
            
            uicontrol('Style','text','Units','characters','String','Drop a group',...
                'FontSize',10,'FontName','Verdana','BackgroundColor',textBackgroundColorRegion2,...
                'Position',[fwidth - 4 - buttonSize(1)*1.25, region2(2)+4.2308, buttonSize(1)*.75,2.6923]);
            %%% change group functions
            %
            uicontrol('Style','text','Units','characters','String',sprintf('Group\nFunction\nBefore'),...
                'FontSize',7,'FontName','Verdana','BackgroundColor',textBackgroundColorRegion2,...
                'Position',[fwidth - 2 - buttonSize(1)*0.5, region2(2)+4.2308, buttonSize(1)*0.5,2.6923]);
            
            hpushbuttonGroupFunctionBefore = uicontrol('Style','pushbutton','Units','characters',...
                'FontSize',20,'FontName','Verdana','BackgroundColor',buttonBackgroundColorRegion2,...
                'String','...',...
                'Position',[fwidth - 2 - buttonSize(1)*0.5, region2(2)+0.7692, buttonSize(1)*.5,buttonSize(2)],...
                'Callback',{@pushbuttonGroupFunctionBefore_Callback});
            
            uicontrol('Style','text','Units','characters','String',sprintf('Group\nFunction\nAfter'),...
                'FontSize',7,'FontName','Verdana','BackgroundColor',textBackgroundColorRegion2,...
                'Position',[fwidth - 2 - buttonSize(1)*0.5, region2(2)+11.1538, buttonSize(1)*0.5,2.6923]);
            
            hpushbuttonGroupFunctionAfter = uicontrol('Style','pushbutton','Units','characters',...
                'FontSize',20,'FontName','Verdana','BackgroundColor',buttonBackgroundColorRegion2,...
                'String','...',...
                'Position',[fwidth - 2 - buttonSize(1)*0.5, region2(2)+7.6923, buttonSize(1)*.5,buttonSize(2)],...
                'Callback',{@pushbuttonGroupFunctionAfter_Callback});
            %%% Change group order
            %
            uicontrol('Style','text','Units','characters','String',sprintf('Move\nGroup\nDown'),...
                'FontSize',7,'FontName','Verdana','BackgroundColor',textBackgroundColorRegion2,...
                'Position',[fwidth - 6 - buttonSize(1)*1.75, region2(2)+4.2308, buttonSize(1)*0.5,2.6923]);
            
            hpushbuttonGroupDown = uicontrol('Style','pushbutton','Units','characters',...
                'FontSize',14,'FontName','Verdana','BackgroundColor',buttonBackgroundColorRegion2,...
                'String','Dn',...
                'Position',[fwidth - 6 - buttonSize(1)*1.75, region2(2)+0.7692, buttonSize(1)*.5,buttonSize(2)],...
                'Callback',{@pushbuttonGroupDown_Callback});
            
            uicontrol('Style','text','Units','characters','String',sprintf('Move\nGroup\nUp'),...
                'FontSize',7,'FontName','Verdana','BackgroundColor',textBackgroundColorRegion2,...
                'Position',[fwidth - 6 - buttonSize(1)*1.75, region2(2)+11.1538, buttonSize(1)*0.5,2.6923]);
            
            hpushbuttonGroupUp = uicontrol('Style','pushbutton','Units','characters',...
                'FontSize',14,'FontName','Verdana','BackgroundColor',buttonBackgroundColorRegion2,...
                'String','Up',...
                'Position',[fwidth - 6 - buttonSize(1)*1.75, region2(2)+7.6923, buttonSize(1)*.5,buttonSize(2)],...
                'Callback',{@pushbuttonGroupUp_Callback});
            %% Assemble Region 3
            %   ___          _            ____
            %  | _ \___ __ _(_)___ _ _   |__ /
            %  |   / -_) _` | / _ \ ' \   |_ \
            %  |_|_\___\__, |_\___/_||_| |___/
            %          |___/
            %%% The position table
            %
            htablePosition = uitable('Units','characters',...
                'BackgroundColor',[textBackgroundColorRegion3;buttonBackgroundColorRegion3],...
                'ColumnName',{'label','position #','X','Y','Z','PFS','PFS offset','function before','function after','# of settings'},...
                'ColumnEditable',logical([1,0,1,1,1,1,1,0,0,0]),...
                'ColumnFormat',{'char','numeric','numeric','numeric','numeric',{'yes','no'},'numeric','char','char','numeric'},...
                'ColumnWidth',{30*ppChar(3) 'auto' 'auto' 'auto' 'auto' 'auto' 'auto' 30*ppChar(3) 30*ppChar(3) 'auto'},...
                'FontSize',8,'FontName','Verdana',...
                'CellEditCallback',@tablePosition_CellEditCallback,...
                'CellSelectionCallback',@tablePosition_CellSelectionCallback,...
                'Position',[region3(1)+2, region3(2)+0.7692, 91.6, 28.1538]);
            %%% add or drop positions
            %
            hpushbuttonPositionAdd = uicontrol('Style','pushbutton','Units','characters',...
                'FontSize',14,'FontName','Verdana','BackgroundColor',buttonBackgroundColorRegion3,...
                'String','Add',...
                'Position',[fwidth - 4 - buttonSize(1)*1.25, region3(2)+14.0769+7.6923, buttonSize(1)*.75,buttonSize(2)],...
                'Callback',{@pushbuttonPositionAdd_Callback});
            
            uicontrol('Style','text','Units','characters','String','Add a position',...
                'FontSize',10,'FontName','Verdana','BackgroundColor',textBackgroundColorRegion3,...
                'Position',[fwidth - 4 - buttonSize(1)*1.25, region3(2)+14.0769+11.1538, buttonSize(1)*.75,2.6923]);
            
            hpushbuttonPositionDrop = uicontrol('Style','pushbutton','Units','characters',...
                'FontSize',14,'FontName','Verdana','BackgroundColor',buttonBackgroundColorRegion3,...
                'String','Drop',...
                'Position',[fwidth - 4 - buttonSize(1)*1.25, region3(2)+14.0769+0.7692, buttonSize(1)*.75,buttonSize(2)],...
                'Callback',{@pushbuttonPositionDrop_Callback});
            
            uicontrol('Style','text','Units','characters','String','Drop a position',...
                'FontSize',10,'FontName','Verdana','BackgroundColor',textBackgroundColorRegion3,...
                'Position',[fwidth - 4 - buttonSize(1)*1.25, region3(2)+14.0769+4.2308, buttonSize(1)*.75,2.6923]);
            %%% change position order
            %
            uicontrol('Style','text','Units','characters','String',sprintf('Move\nPosition\nDown'),...
                'FontSize',7,'FontName','Verdana','BackgroundColor',textBackgroundColorRegion3,...
                'Position',[fwidth - 6 - buttonSize(1)*1.75, region3(2)+14.0769+4.2308, buttonSize(1)*0.5,2.6923]);
            
            hpushbuttonPositionDown = uicontrol('Style','pushbutton','Units','characters',...
                'FontSize',14,'FontName','Verdana','BackgroundColor',buttonBackgroundColorRegion3,...
                'String','Dn',...
                'Position',[fwidth - 6 - buttonSize(1)*1.75, region3(2)+14.0769+0.7692, buttonSize(1)*.5,buttonSize(2)],...
                'Callback',{@pushbuttonPositionDown_Callback});
            
            uicontrol('Style','text','Units','characters','String',sprintf('Move\nPosition\nUp'),...
                'FontSize',7,'FontName','Verdana','BackgroundColor',textBackgroundColorRegion3,...
                'Position',[fwidth - 6 - buttonSize(1)*1.75, region3(2)+14.0769+11.1538, buttonSize(1)*0.5,2.6923]);
            
            hpushbuttonPositionUp = uicontrol('Style','pushbutton','Units','characters',...
                'FontSize',14,'FontName','Verdana','BackgroundColor',buttonBackgroundColorRegion3,...
                'String','Up',...
                'Position',[fwidth - 6 - buttonSize(1)*1.75, region3(2)+14.0769+7.6923, buttonSize(1)*.5,buttonSize(2)],...
                'Callback',{@pushbuttonPositionUp_Callback});
            %%% move to a position
            %
            hpushbuttonPositionMove = uicontrol('Style','pushbutton','Units','characters',...
                'FontSize',14,'FontName','Verdana','BackgroundColor',buttonBackgroundColorRegion3,...
                'String','Move',...
                'Position',[fwidth - 6 - buttonSize(1)*1.75, region3(2)+7.6923, buttonSize(1),buttonSize(2)],...
                'Callback',{@pushbuttonPositionMove_Callback});
            
            uicontrol('Style','text','Units','characters','String',sprintf('Move the stage\nto the\nselected position'),...
                'FontSize',7,'FontName','Verdana','BackgroundColor',textBackgroundColorRegion3,...
                'Position',[fwidth - 6 - buttonSize(1)*1.75, region3(2)+11.1538, buttonSize(1),2.6923]);
            %%% change a position value to the current position
            %
            hpushbuttonPositionSet = uicontrol('Style','pushbutton','Units','characters',...
                'FontSize',14,'FontName','Verdana','BackgroundColor',buttonBackgroundColorRegion3,...
                'String','Set',...
                'Position',[fwidth - 6 - buttonSize(1)*1.75, region3(2)+0.7692, buttonSize(1),buttonSize(2)],...
                'Callback',{@pushbuttonPositionSet_Callback});
            
            uicontrol('Style','text','Units','characters','String',sprintf('Set the position\nto the current\nstage position'),...
                'FontSize',7,'FontName','Verdana','BackgroundColor',textBackgroundColorRegion3,...
                'Position',[fwidth - 6 - buttonSize(1)*1.75, region3(2)+4.2308, buttonSize(1),2.6923]);
            %%% add a grid
            %
            hpushbuttonSetAllZ = uicontrol('Style','pushbutton','Units','characters',...
                'FontSize',10,'FontName','Verdana','BackgroundColor',buttonBackgroundColorRegion3,...
                'String',sprintf('Set All Z'),...
                'Position',[fwidth - 2 - buttonSize(1)*.75, region3(2)+7.6923, buttonSize(1)*.75,buttonSize(2)],...
                'Callback',{@pushbuttonSetAllZ_Callback});
            
            uicontrol('Style','text','Units','characters','String',sprintf('Add a grid\nof positions'),...
                'FontSize',7,'FontName','Verdana','BackgroundColor',textBackgroundColorRegion3,...
                'Position',[fwidth - 2 - buttonSize(1)*.75, region3(2)+11.1538, buttonSize(1)*.75,2.6923]);
            %%% change position functions
            %
            uicontrol('Style','text','Units','characters','String',sprintf('Position\nFunction\nBefore'),...
                'FontSize',7,'FontName','Verdana','BackgroundColor',textBackgroundColorRegion3,...
                'Position',[fwidth - 2 - buttonSize(1)*0.5, region3(2)+14.0769+4.2308, buttonSize(1)*0.5,2.6923]);
            
            hpushbuttonPositionFunctionBefore = uicontrol('Style','pushbutton','Units','characters',...
                'FontSize',20,'FontName','Verdana','BackgroundColor',buttonBackgroundColorRegion3,...
                'String','...',...
                'Position',[fwidth - 2 - buttonSize(1)*0.5, region3(2)+14.0769+0.7692, buttonSize(1)*.5,buttonSize(2)],...
                'Callback',{@pushbuttonPositionFunctionBefore_Callback});
            
            uicontrol('Style','text','Units','characters','String',sprintf('Position\nFunction\nAfter'),...
                'FontSize',7,'FontName','Verdana','BackgroundColor',textBackgroundColorRegion3,...
                'Position',[fwidth - 2 - buttonSize(1)*0.5, region3(2)+14.0769+11.1538, buttonSize(1)*0.5,2.6923]);
            
            hpushbuttonPositionFunctionAfter = uicontrol('Style','pushbutton','Units','characters',...
                'FontSize',20,'FontName','Verdana','BackgroundColor',buttonBackgroundColorRegion3,...
                'String','...',...
                'Position',[fwidth - 2 - buttonSize(1)*0.5, region3(2)+14.0769+7.6923, buttonSize(1)*.5,buttonSize(2)],...
                'Callback',{@pushbuttonPositionFunctionAfter_Callback});
            %% Assemble Region 4
            %   ___          _            _ _
            %  | _ \___ __ _(_)___ _ _   | | |
            %  |   / -_) _` | / _ \ ' \  |_  _|
            %  |_|_\___\__, |_\___/_||_|   |_|
            %          |___/
            %%% The settings table
            %
            
            htableSettings = uitable('Units','characters',...
                'BackgroundColor',[textBackgroundColorRegion4;buttonBackgroundColorRegion4],...
                'ColumnName',{'channel','exposure','binning','Z step size','Z upper','Z lower','# of Z steps','Z offset','period mult.','function','settings #'},...
                'ColumnEditable',logical([1,1,1,1,1,1,0,1,1,0,0]),...
                'ColumnFormat',{transpose(obj.mm.Channel),'numeric','numeric','numeric','numeric','numeric','numeric','numeric','numeric','char','numeric'},...
                'ColumnWidth',{'auto' 'auto' 'auto' 'auto' 'auto' 'auto' 'auto' 'auto' 'auto' 'auto' 'auto'},...
                'FontSize',8,'FontName','Verdana',...
                'CellEditCallback',@tableSettings_CellEditCallback,...
                'CellSelectionCallback',@tableSettings_CellSelectionCallback,...
                'Position',[region4(1)+2, region4(2)+0.7692, 79.6, 13.0769]);
            %%% add or drop a group
            %
            hpushbuttonSettingsAdd = uicontrol('Style','pushbutton','Units','characters',...
                'FontSize',14,'FontName','Verdana','BackgroundColor',buttonBackgroundColorRegion4,...
                'String','Add',...
                'Position',[fwidth - 6 - buttonSize(1)*1.75, region4(2)+7.6923, buttonSize(1)*.75,buttonSize(2)],...
                'Callback',{@pushbuttonSettingsAdd_Callback});
            
            uicontrol('Style','text','Units','characters','String','Add a settings',...
                'FontSize',10,'FontName','Verdana','BackgroundColor',textBackgroundColorRegion4,...
                'Position',[fwidth - 6 - buttonSize(1)*1.75, region4(2)+11.1538, buttonSize(1)*.75,2.6923]);
            
            hpushbuttonSettingsDrop = uicontrol('Style','pushbutton','Units','characters',...
                'FontSize',14,'FontName','Verdana','BackgroundColor',buttonBackgroundColorRegion4,...
                'String','Drop',...
                'Position',[fwidth - 6 - buttonSize(1)*1.75, region4(2)+0.7692, buttonSize(1)*.75,buttonSize(2)],...
                'Callback',{@pushbuttonSettingsDrop_Callback});
            
            uicontrol('Style','text','Units','characters','String','Drop a settings',...
                'FontSize',10,'FontName','Verdana','BackgroundColor',textBackgroundColorRegion4,...
                'Position',[fwidth - 6 - buttonSize(1)*1.75, region4(2)+4.2308, buttonSize(1)*.75,2.6923]);
            %%% change Settings functions
            %
            uicontrol('Style','text','Units','characters','String',sprintf('Settings\nFunction'),...
                'FontSize',7,'FontName','Verdana','BackgroundColor',textBackgroundColorRegion4,...
                'Position',[fwidth - 2 - buttonSize(1)*0.5, region4(2)+11.1538, buttonSize(1)*0.5,2.6923]);
            
            hpushbuttonSettingsFunction = uicontrol('Style','pushbutton','Units','characters',...
                'FontSize',20,'FontName','Verdana','BackgroundColor',buttonBackgroundColorRegion4,...
                'String','...',...
                'Position',[fwidth - 2 - buttonSize(1)*0.5, region4(2)+7.6923, buttonSize(1)*.5,buttonSize(2)],...
                'Callback',{@pushbuttonSettingsFunction_Callback});
            %%% Change Settings order
            %
            uicontrol('Style','text','Units','characters','String',sprintf('Move\nSettings\nDown'),...
                'FontSize',7,'FontName','Verdana','BackgroundColor',textBackgroundColorRegion4,...
                'Position',[fwidth - 8 - buttonSize(1)*2.25, region4(2)+4.2308, buttonSize(1)*0.5,2.6923]);
            
            hpushbuttonSettingsDown = uicontrol('Style','pushbutton','Units','characters',...
                'FontSize',14,'FontName','Verdana','BackgroundColor',buttonBackgroundColorRegion4,...
                'String','Dn',...
                'Position',[fwidth - 8 - buttonSize(1)*2.25, region4(2)+0.7692, buttonSize(1)*.5,buttonSize(2)],...
                'Callback',{@pushbuttonSettingsDown_Callback});
            
            uicontrol('Style','text','Units','characters','String',sprintf('Move\nSettings\nUp'),...
                'FontSize',7,'FontName','Verdana','BackgroundColor',textBackgroundColorRegion4,...
                'Position',[fwidth - 8 - buttonSize(1)*2.25, region4(2)+11.1538, buttonSize(1)*0.5,2.6923]);
            
            hpushbuttonSettingsUp = uicontrol('Style','pushbutton','Units','characters',...
                'FontSize',14,'FontName','Verdana','BackgroundColor',buttonBackgroundColorRegion4,...
                'String','Up',...
                'Position',[fwidth - 8 - buttonSize(1)*2.25, region4(2)+7.6923, buttonSize(1)*.5,buttonSize(2)],...
                'Callback',{@pushbuttonSettingsUp_Callback});
            %%% Set Z upper or Z lower boundaries
            %
            uicontrol('Style','text','Units','characters','String',sprintf('Set Z\nLower'),...
                'FontSize',7,'FontName','Verdana','BackgroundColor',textBackgroundColorRegion4,...
                'Position',[fwidth - 4 - buttonSize(1), region4(2)+4.2308, buttonSize(1)*0.5,2.6923]);
            
            hpushbuttonSettingsZLower = uicontrol('Style','pushbutton','Units','characters',...
                'FontSize',14,'FontName','Verdana','BackgroundColor',buttonBackgroundColorRegion4,...
                'String','Z-',...
                'Position',[fwidth - 4 - buttonSize(1), region4(2)+0.7692, buttonSize(1)*.5,buttonSize(2)],...
                'Callback',{@pushbuttonSettingsZLower_Callback});
            
            uicontrol('Style','text','Units','characters','String',sprintf('Set Z\nUpper'),...
                'FontSize',7,'FontName','Verdana','BackgroundColor',textBackgroundColorRegion4,...
                'Position',[fwidth - 4 - buttonSize(1), region4(2)+11.1538, buttonSize(1)*0.5,2.6923]);
            
            hpushbuttonSettingsZUpper = uicontrol('Style','pushbutton','Units','characters',...
                'FontSize',14,'FontName','Verdana','BackgroundColor',buttonBackgroundColorRegion4,...
                'String','Z+',...
                'Position',[fwidth - 4 - buttonSize(1), region4(2)+7.6923, buttonSize(1)*.5,buttonSize(2)],...
                'Callback',{@pushbuttonSettingsZUpper_Callback});
            %% Handles
            %   _  _              _ _
            %  | || |__ _ _ _  __| | |___ ___
            %  | __ / _` | ' \/ _` | / -_|_-<
            %  |_||_\__,_|_||_\__,_|_\___/__/
            %
            % store the uicontrol handles in the figure handles via guidata()
            handles.popupmenuUnitsOfTime = hpopupmenuUnitsOfTime;
            handles.editFundamentalPeriod = heditFundamentalPeriod;
            handles.editDuration = heditDuration;
            handles.editNumberOfTimepoints = heditNumberOfTimepoints;
            handles.editOutputDirectory = heditOutputDirectory;
            handles.pushbuttonOutputDirectory = hpushbuttonOutputDirectory;
            handles.pushbuttonSave = hpushbuttonSave;
            handles.pushbuttonLoad = hpushbuttonLoad;
            handles.pushbuttonGroupAdd = hpushbuttonGroupAdd;
            handles.pushbuttonGroupDrop = hpushbuttonGroupDrop;
            handles.pushbuttonGroupFunctionBefore = hpushbuttonGroupFunctionBefore;
            handles.pushbuttonGroupFunctionAfter = hpushbuttonGroupFunctionAfter;
            handles.pushbuttonGroupDown = hpushbuttonGroupDown;
            handles.pushbuttonGroupUp = hpushbuttonGroupUp;
            handles.pushbuttonPositionAdd = hpushbuttonPositionAdd;
            handles.pushbuttonPositionDown = hpushbuttonPositionDown;
            handles.pushbuttonPositionDrop = hpushbuttonPositionDrop;
            handles.pushbuttonPositionFunctionAfter = hpushbuttonPositionFunctionAfter;
            handles.pushbuttonPositionFunctionBefore = hpushbuttonPositionFunctionBefore;
            handles.pushbuttonPositionMove = hpushbuttonPositionMove;
            handles.pushbuttonPositionSet = hpushbuttonPositionSet;
            handles.pushbuttonPositionUp = hpushbuttonPositionUp;
            handles.pushbuttonSettingsAdd = hpushbuttonSettingsAdd;
            handles.pushbuttonSettingsDown = hpushbuttonSettingsDown;
            handles.pushbuttonSettingsDrop = hpushbuttonSettingsDrop;
            handles.pushbuttonSettingsFunction = hpushbuttonSettingsFunction;
            handles.pushbuttonSettingsUp = hpushbuttonSettingsUp;
            handles.pushbuttonSettingsZUpper = hpushbuttonSettingsZUpper;
            handles.pushbuttonSettingsZLower = hpushbuttonSettingsZLower;
            handles.tableGroup = htableGroup;
            handles.tablePosition = htablePosition;
            handles.tableSettings = htableSettings;
            guidata(f,handles);
            %%%
            % make the gui visible
            set(f,'Visible','on');
            
            obj.gui_main = f;
            obj.refresh_gui_main;
        end
        %%
        %
        function obj = popupmenuUnitsOfTime_Callback(obj,~,~)
            handles = guidata(obj.gui_main);
            seconds2array = [1,60,3600,86400];
            obj.uot_conversion = seconds2array(handles.popupmenuUnitsOfTime.Value);
            obj.refresh_gui_main;
        end
        %%
        %
        function obj = refresh_gui_main(obj)
            handles = guidata(obj.gui_main);
            %% Region 1
            %
            %% Time elements
            %
            set(handles.editFundamentalPeriod,'String',num2str(obj.itinerary.fundamental_period/obj.uot_conversion));
            set(handles.editDuration,'String',num2str(obj.itinerary.duration/obj.uot_conversion));
            set(handles.editNumberOfTimepoints,'String',num2str(obj.itinerary.number_of_timepoints));
            %% Output Directory
            %
            set(handles.editOutputDirectory,'String',obj.itinerary.output_directory);
            %% Region 2
            %
            %% Group Table
            % Show the data in the itinerary |group_order| property
            tableGroupData = cell(obj.itinerary.number_group,...
                length(get(handles.tableGroup,'ColumnName')));
            n=1;
            for i = obj.itinerary.order_group
                tableGroupData{n,1} = obj.itinerary.group_label{i};
                tableGroupData{n,2} = i;
                tableGroupData{n,3} = obj.itinerary.number_position(i);
                tableGroupData{n,4} = obj.itinerary.group_function_before{i};
                tableGroupData{n,5} = obj.itinerary.group_function_after{i};
                n = n + 1;
            end
            set(handles.tableGroup,'Data',tableGroupData);
            %% Region 3
            %
            %% Position Table
            % Show the data in the itinerary |position_order| property for a given
            % group
            myGroupOrder = obj.itinerary.order_group;
            gInd = myGroupOrder(obj.pointerGroup(1));
            myPositionOrder = obj.itinerary.order_position{gInd};
            tablePositionData = cell(length(myPositionOrder),...
                length(get(handles.tablePosition,'ColumnName')));
            n=1;
            for i = myPositionOrder
                tablePositionData{n,1} = obj.itinerary.position_label{i};
                tablePositionData{n,2} = i;
                tablePositionData{n,3} = obj.itinerary.position_xyz(i,1);
                tablePositionData{n,4} = obj.itinerary.position_xyz(i,2);
                tablePositionData{n,5} = obj.itinerary.position_xyz(i,3);
                if obj.itinerary.position_continuous_focus_bool(i)
                    tablePositionData{n,6} = 'yes';
                else
                    tablePositionData{n,6} = 'no';
                end
                tablePositionData{n,7} = obj.itinerary.position_continuous_focus_offset(i);
                tablePositionData{n,8} = obj.itinerary.position_function_before{i};
                tablePositionData{n,9} = obj.itinerary.position_function_after{i};
                tablePositionData{n,10} = obj.itinerary.number_settings(i);
                n = n + 1;
            end
            set(handles.tablePosition,'Data',tablePositionData);
            %% Region 4
            %
            %% Settings Table
            % Show the prototype_settings
            pInd = obj.itinerary.ind_position{gInd};
            pInd = pInd(1);
            mySettingsOrder = obj.itinerary.order_settings{pInd};
            tableSettingsData = cell(length(mySettingsOrder),...
                length(get(handles.tableSettings,'ColumnName')));
            n=1;
            for i = mySettingsOrder
                tableSettingsData{n,1} = obj.mm.Channel{obj.itinerary.settings_channel(i)};
                tableSettingsData{n,2} = obj.itinerary.settings_exposure(i);
                tableSettingsData{n,3} = obj.itinerary.settings_binning(i);
                tableSettingsData{n,5} = obj.itinerary.settings_z_step_size(i);
                tableSettingsData{n,6} = obj.itinerary.settings_z_stack_upper_offset(i);
                tableSettingsData{n,7} = obj.itinerary.settings_z_stack_lower_offset(i);
                tableSettingsData{n,8} = length(obj.itinerary.settings_z_stack_lower_offset(i)...
                    :obj.itinerary.settings_z_step_size(i)...
                    :obj.itinerary.settings_z_stack_upper_offset(i));
                tableSettingsData{n,9} = obj.itinerary.settings_z_origin_offset(i);
                tableSettingsData{n,10} = obj.itinerary.settings_period_multiplier(i);
                tableSettingsData{n,11} = obj.itinerary.settings_function{i};
                tableSettingsData{n,12} = i;
                n = n + 1;
            end
            set(handles.tableSettings,'Data',tableSettingsData);
        end
    end
end