%% Core_twitter
% Core_twitter wraps the Python Tweepy package. When MATLAB is properly
% configured with Python Core_twitter can be used to update the user's
% Twitter status. The Tweepy API is a property of this object, so other all
% the Tweepy methods can be accessed, or integrated more seemlessly into
% MATLAB with further coding. Go to github.com/tweepy/tweepy for more
% information.
%
% This file was last updated in Oct. 2015.
%
% How to configure Python and Tweepy in MATLAB 2015b (on a Windows Box):
% # Download Python 3.4 from python.org/downloads/. Ensure that the 32-bit
% or 64-bit version of Python is consistent with MATLAB.
% # Update the Windows Path Environment Variable to include the Python path
% and the PythonXX\Scripts path.
% # From the Command Prompt as an Administrator use the _pip_ command to
% install Tweepy, e.g. _C:\>pip install tweepy_
% # Update the _twitter.txt_ file by copying and pasting the four codes
% generated by the *Manage Your Apps* tool at dev.twitter.com. The text
% file is a comma-separated-value table. Make sure the permissions include
% _Write_ when the codes are generated.

classdef Core_twitter < handle
    %%
    %
    properties
        active = false;
        tweepyAPI
    end
    
    methods
        %% The constructor
        % 
        function obj = Core_twitter()
            [mfilepath,~,~] = fileparts(mfilename('fullpath'));
            %%
            % Is Python installed?
            [pyVer,pyExe,pyIs] = pyversion;
            if pyIs
                mystr = sprintf('Python Version: %s\nPython Executable: %s',pyVer,pyExe);
                disp(mystr);
            else
                error('crtwt:nopy','MATLAB is not configured for python.');
            end
            %%
            % Is Tweepy package installed?
            pyTweepyIs = py.importlib.find_loader('tweepy');
            if isa(pyTweepyIs,'py.NoneType')
                error('crtwt:notwt','Python Tweepy is not found. Use ''pip'' to install ''tweepy''.');
            else
                disp('Tweepy found!');
            end
            %%
            % Does the twitter credentials file exist?
            if exist(fullfile(mfilepath,'twitter.txt'),'file')
                disp('Twitter credentials found!');
            else
                error('crtwt:nocred','User generated Twitter credentials are not found.');
            end
            twitterCredentials = readtable(fullfile(mfilepath,'twitter.txt'));
            auth = py.tweepy.OAuthHandler(twitterCredentials.ConsumerKey{1},twitterCredentials.ConsumerSecret{1});
            auth.set_access_token(twitterCredentials.AccessToken{1},twitterCredentials.AccessTokenSecret{1});
            obj.tweepyAPI = py.tweepy.API(auth);
            obj.active = true;
        end
        %% update_status
        % Change the Twitter status.
        function obj = update_status(obj,status)
            try
                obj.tweepyAPI.update_status(pyargs('status',status));
            catch
                disp('Twitter status failed to update. The message may be too long, or the message may be a repeat.');
            end
        end
    end
end