%% Core_twitter
% Core_twitter wraps the Python Tweepy package. When MATLAB is properly
% configured with Python Core_twitter can be used to update the user's
% Twitter status. The Tweepy API is a property of this object, so all other
% Tweepy methods can be accessed, too; or integrated more seemlessly into
% MATLAB with further coding. Go to <github.com/tweepy/tweepy> for more
% information.
%
% How to configure Python and Tweepy in MATLAB 2015b (on a Windows Box):
%
% # Download Python 3.4 from <python.org/downloads/>. Ensure that the 32-bit
% or 64-bit version of Python is consistent with MATLAB.
% # Update the Windows Path Environment Variable to include the Python path
% and the _PythonXX\Scripts_ path.
% # From the Command Prompt as an Administrator use the |pip| command to
% install Tweepy, e.g. |C:\>pip install tweepy|
% # Update the _twitter.txt_ file by copying and pasting the four codes
% generated by the *Manage Your Apps* tool at dev.twitter.com. The text
% file is a comma-separated-value table. Make sure the permissions include
% _Write_ when the codes are generated.

classdef core_twitter < handle
    %%
    % 
    properties
        active = false;
        tweepyAPI
        verifyBool = false;
    end
    
    methods
        %% The constructor
        % 
        function obj = core_twitter()
            [mfilepath,~,~] = fileparts(mfilename('fullpath'));
            %%%
            % Is Python installed?
            [pyVer,pyExe,pyIs] = pyversion;
            if pyIs
                mystr = sprintf('Python Version: %s\nPython Executable: %s',pyVer,pyExe);
                disp(mystr);
            else
                warning('crtwt:nopy','MATLAB is not configured for python.');
                return
            end
            %%%
            % Is Tweepy package installed?
            pyTweepyIs = py.importlib.find_loader('tweepy');
            if isa(pyTweepyIs,'py.NoneType')
                warning('crtwt:notwt','Python Tweepy is not found. Use ''pip'' to install ''tweepy''.');
                return
            else
                disp('Tweepy found!');
            end
            %%%
            % Does the twitter credentials file exist?
            if exist(fullfile(mfilepath,'twitter.txt'),'file')
                disp('Twitter credentials found!');
            else
                warning('crtwt:nocred','User generated Twitter credentials are not found.');
                return
            end
            %%%
            % Verify Twitter can authenticate this "app"
            twitterCredentials = readtable(fullfile(mfilepath,'twitter.txt'));
            auth = py.tweepy.OAuthHandler(twitterCredentials.ConsumerKey{1},twitterCredentials.ConsumerSecret{1});
            auth.set_access_token(twitterCredentials.AccessToken{1},twitterCredentials.AccessTokenSecret{1});
            obj.tweepyAPI = py.tweepy.API(auth);
            obj.verify_credentials;
            if obj.verifyBool
                obj.active = true;
            else
                obj.active = false;
            end
        end
        %% update_status
        % Change the Twitter status.
        function obj = update_status(obj,status)
            if ~obj.active
                return
            end
            try
                obj.tweepyAPI.update_status(pyargs('status',status));
            catch
                disp('Twitter status failed to update. The message may be too long, or the message may be a repeat.');
            end
        end
        %% verify_credentials
        %
        function verifyBool = verify_credentials(obj)
            try
                obj.tweepyAPI.verify_credentials;
                disp('User''s Twitter account has been authenticated.');
                verifyBool = true;
            catch
                warning('crtwt:notvalid','Twitter could not authenticate the app, because one or more tokens/keys are incorrect.');
                verifyBool = false;
            end
            obj.verifyBool = verifyBool;
        end
    end
end